// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class HeatLoss1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void heatLoss1() {
    driver.Navigate().GoToUrl("https://kermi-fko.ru/");
    driver.Manage().Window.Size = new System.Drawing.Size(736, 666);
    driver.FindElement(By.LinkText("Расчеты")).Click();
    driver.FindElement(By.XPath("//span[contains(.,\'Расчет теплопотерь дома\')]")).Click();
    driver.FindElement(By.Id("country")).Click();
    {
      var dropdown = driver.FindElement(By.Id("country"));
      dropdown.FindElement(By.XPath("//option[. = 'Белорусь']")).Click();
    }
    driver.FindElement(By.Id("city2")).Click();
    {
      var dropdown = driver.FindElement(By.Id("city2"));
      dropdown.FindElement(By.XPath("//option[. = 'Минск']")).Click();
    }
    driver.FindElement(By.Id("outdoor_t")).Click();
    driver.FindElement(By.CssSelector(".pmid-38840 > div > .t_losses tr:nth-child(2)")).Click();
    driver.FindElement(By.Id("outdoor_t")).SendKeys("-22");
    driver.FindElement(By.Id("indoor_t")).Click();
    driver.FindElement(By.Id("indoor_t")).SendKeys("22");
    driver.FindElement(By.CssSelector(".hv > .change_im_h2")).Click();
    js.ExecuteScript("window.scrollTo(0,301.3333435058594)");
    driver.FindElement(By.Id("facade")).Click();
    {
      var dropdown = driver.FindElement(By.Id("facade"));
      dropdown.FindElement(By.XPath("//option[. = 'С вентилируемой воздушной прослойкой']")).Click();
    }
    driver.FindElement(By.Id("walls_area")).Click();
    driver.FindElement(By.Id("walls_area")).SendKeys("100");
    driver.FindElement(By.Id("wall_mat_1")).Click();
    {
      var dropdown = driver.FindElement(By.Id("wall_mat_1"));
      dropdown.FindElement(By.XPath("//option[. = 'Минеральная вата']")).Click();
    }
    driver.FindElement(By.Id("layer_thickness_1")).Click();
    driver.FindElement(By.Id("layer_thickness_1")).SendKeys("0.3");
    driver.FindElement(By.Name("button")).Click();
    driver.FindElement(By.Id("wall_losses")).Click();
  }
}
